on:
  push:
    branches:
      - master
name: Auto Deploy to AWS
jobs:
  deploy:
    name: Auto Deploy
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install Dependencies
        run: |
          yarn global add serverless
          cd backend
          yarn
          yarn tsc
          rm -rf src
          cd ..
          cd frontend && yarn && cd ..

      - name: Deploy to AWS
        run: |
          cd backend && $(yarn global bin)/serverless deploy && cd ..
          cd frontend && $(yarn global bin)/serverless && cd ..
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
